name: CD Release & Deploy

on:
  push:
    branches: [ main ]
    tags: [ 'v*..' ]

permissions:
  contents: write

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  create-github-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Nueva versión: ${{ github.ref_name }}
            Generado automáticamente por CD.
          draft: false
          prerelease: false

  deploy-to-render:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Ensure jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Trigger Render deploy (commit de main)
        id: trigger
        run: |
          set -euo pipefail
          # Validar secrets presentes
          : "${RENDER_API_KEY:?Falta RENDER_API_KEY}"
          : "${RENDER_SERVICE_ID:?Falta RENDER_SERVICE_ID}"

          # Body mínimo. En general NO hace falta commitId.
          BODY='{}'
          # Si querés forzar commitId, descomentá:
          # BODY=$(jq -n --arg c "$COMMIT_SHA" '{commitId:$c}')

          # Llamar a Render y fallar si HTTP != 2xx
          RESP=$(curl -fsS -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -d "$BODY")

          echo "Respuesta Render: $RESP"

          DEPLOY_ID=$(echo "$RESP" | jq -r '.id // empty')
          if [ -z "$DEPLOY_ID" ]; then
            MSG=$(echo "$RESP" | jq -r '.message? // .error? // empty')
            echo "No se obtuvo deploy_id de Render. Mensaje: ${MSG:-desconocido}"
            exit 1
          fi

          echo "deploy_id=$DEPLOY_ID" >> "$GITHUB_OUTPUT"

      - name: Wait until deploy is live
        run: |
          set -euo pipefail
          DEPLOY_ID="${{ steps.trigger.outputs.deploy_id }}"
          echo "Esperando deploy $DEPLOY_ID ..."
          for i in $(seq 1 90); do
            STATUS_JSON=$(curl -fsS -H "Authorization: Bearer ${RENDER_API_KEY}" \
              "https://api.render.com/v1/deploys/${DEPLOY_ID}")
            PHASE=$(echo "$STATUS_JSON" | jq -r '.status')
            echo "Intento $i → status=$PHASE"
            if [ "$PHASE" = "live" ]; then
              echo "✅ Deploy live"; exit 0
            elif [ "$PHASE" = "failed" ]; then
              echo "❌ Deploy failed"; echo "$STATUS_JSON"; exit 1
            fi
            sleep 10
          done
          echo "⏱ Timeout esperando el deploy"; exit 1